parameters:
    flowvox.transcription.default_provider: '%env(string:FLOWVOX_TRANSCRIPTION_PROVIDER)%'
    flowvox.whisper.mode: '%env(string:FLOWVOX_WHISPER_MODE)%'
    openai_key_empty: ''
    whisper_stream_language_default: 'fr'
    whisper_stream_length_ms_default: 30000
    whisper_stream_vad_default: '0.6'
    whisper_stream_threads_default: 6
